---
title: "data exploration"
author: "Supraja Battula"
date: "3/10/2022"
output: html_document
---


```{r}
library(lubridate)
library(tidyr)
library(dplyr)
library(ggplot2)

df = read.csv("traffic_violaions.csv",
              na.strings=c("","NA"))
df$search_type[is.na(df$search_type)] = "unknown" # add a new level unknown
# factor variables
df$driver_gender = as.factor(df$driver_gender)
df$driver_race = as.factor(df$driver_race)
df$violation_raw = as.factor(df$violation_raw)
df$violation = as.factor(df$violation)
df$search_type = as.factor(df$search_type)
df$stop_outcome = as.factor(df$stop_outcome)
df$stop_duration = as.factor(df$stop_duration)
df$stop_date = as.Date(mdy(df$stop_date)) # date variable
df = df[, -c(3, 5, 8)] #drop country_name, two raw variables

df = df %>% 
  drop_na()
```

```{r}
#count of race:
df %>% ggplot()+
  geom_bar(aes(x=driver_race))


#duration of stop and race: 
df %>% ggplot()+
  geom_bar(aes(x=stop_duration,fill=driver_race))

#type of violation against race:
df %>% ggplot()+
  geom_bar(aes(x=violation,fill=driver_race))

#violation type against gender:
ggplot(df)+
  geom_bar(aes(violation,fill=driver_gender))

#age
df %>% ggplot() +
  geom_histogram(aes(x=driver_age, fill=violation))
```


