---
title: "Milestone3"
output: html_document
---
```{r packages}
library(shiny)
library(tidyverse)
library(lubridate)
library(readr)
library(patchwork)
```

```{r clean}
## change file path
df = read_csv("traffic_violations.csv")
## no changes to the following code
df$search_type[is.na(df$search_type)] = "unknown" # add a new level unknown
# factor variables
df$driver_gender = as.factor(df$driver_gender)
df$driver_race = as.factor(df$driver_race)
df$violation_raw = as.factor(df$violation_raw)
df$violation = as.factor(df$violation)
df$search_type = as.factor(df$search_type)
df$stop_outcome = as.factor(df$stop_outcome)
df$stop_duration = as.factor(df$stop_duration)
df$stop_date = as.Date(mdy(df$stop_date)) # date variable
df = df[, -c(3, 5, 8)] #drop country_name, two raw variables
df = df %>% drop_na()
```

```{r helper methods}
## used in brushing to select the stop date
reset_selection <- function(x, brush) {
  brushedPoints(x, brush, allRows = TRUE)$selected_
}

## create the histogram using in brushing
## x axis is the stop date of the traffic violation
## the height of each bar represents the total number of violation at the stop date
## in m2, we planned to over the scatterplot, but it looks too messy so I changed to hist
hist_brushed <- function(df) {
  df %>%
    mutate(n = 1) %>%
    group_by(stop_date) %>%
    summarise(n = sum(n)) %>%
    ggplot(aes(stop_date, n)) +
    geom_col()+
    xlab("Stop date of the traffic violation")+
    ylab("Total number of violation cases")+
    ggtitle("Total number of violation over the stop date")
}

## create the frequency table for the search_type
table_search <- function(df){
  df %>%
    mutate(n = 1) %>%
    group_by(search_type) %>%
    summarise(n = sum(n))
}

## create a bar plot for a given variable 
plot_bar = function(df,x,col_var){
  df%>%
    ggplot(aes(get(x), fill = get(col_var)))+
    geom_bar()+
    labs(title = paste(x,"patterns by",col_var), x=x, fill = col_var)
}

## combine two subplots (stop outcome and violation)
combine = function(df, col_var){
  p = list()
  p[["stop_plot"]] = plot_bar(df,"stop_outcome", col_var)
  p[["vio_plot"]] = plot_bar(df,"violation", col_var)
  p[["stop_plot"]] + p[["vio_plot"]]+
    plot_layout(guides = "collect")&
    plot_annotation(theme=theme(legend.position = "right"))
}

```



```{r}
ui <- fluidPage(
  titlePanel("Traffic Violation"),
  
  sidebarLayout(
    sidebarPanel(
      sliderInput("age", "Age", c(40,60), min = 15, max = 88, step = 1),
      checkboxGroupInput("gender", "Gender", choices = unique(df$driver_gender), 
                         selected = unique(df$driver_gender)), 
      # can only select one value ?change?
      selectInput("race", "Race", c("White","Black","Asian","Hispanic","Other"),unique(df$driver_race), multiple = TRUE), 
      plotOutput("hist_brushed", brush = brushOpts("plot_brush", direction = "x"))),
    
    mainPanel(
      selectInput("color", "Select a variable you want to color in:", list("race","gender")),
      plotOutput("bar_vio_stop"), 
      #compound figure of the number of different violation types and stop types 
      plotOutput("bar_arr"), # a stacked bar plot: relationship between whether arrested and drug-related stops
      dataTableOutput("table_search"), #frequency table of search types
      dataTableOutput("table")) #the complete subset of the data
    )
  )


server <- function(input, output) {
  df_sub_brushed <- reactive({
    brushedPoints(df, input$plot_brush) %>%
      filter((driver_race %in% input$race),
             driver_gender %in% input$gender,
             driver_age >= input$age[1],
             driver_age <= input$age[2])
   })
  
  df_sub_unbrushed <- reactive({
    df %>%
      filter((driver_race %in% input$race),
             driver_gender %in% input$gender,
             driver_age >= input$age[1],
             driver_age <= input$age[2])
   })
  selected <- reactiveVal(rep(TRUE, nrow(df)))
  observeEvent(
    input$plot_brush,
    selected(reset_selection(df, input$plot_brush))
  )
  
  output$hist_brushed <- renderPlot(hist_brushed(df_sub_unbrushed()))
  output$table <- renderDataTable(df_sub_brushed())
  output$table_search = renderDataTable(table_search(df_sub_brushed()))
  output$bar_vio_stop = renderPlot(combine(df_sub_unbrushed(), paste("driver_",input$color, sep = "")))
}

app <- shinyApp(ui, server)
app
```

